# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  reference-package-directory: ./reference-package

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Set up a specific version of Python and add the command-line tools to the PATH
    - name: Setup Python
      uses: actions/setup-python@v1.2.0

    - name: Install cookiecutter
      run: pip install cookiecutter        

    - name: Cookiecut the template
      run: cookiecutter $GITHUB_WORKSPACE --no-input

    - name: Setup node
      uses: actions/setup-node@v1

    # Runs a set of commands using the runners shell
    - name: Install npm packages
      working-directory: ${{env.reference-package-directory}}
      run: |
        npm install

    - name: Run npm scripts
      working-directory: ${{env.reference-package-directory}}
      run: |
        npm run format
        npm run lint
        npm test
        npm run build

    - name: Run npm publish
      working-directory: ${{env.reference-package-directory}}
      run: |
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}             
  